
output: main.o
	gcc main.o -o output


main.o: main.cpp
	gcc -c main.cpp


clean:
	rm *.o output

\\incercare esuata de a implementa Makefiles. Am intampinat dificultati in lucrul cu bash-ul disponibil in pachetul Latex pentru Windows 10.
